### ISSUE TITLE
more xdg_types

### ISSUE THREAD

**Issue by star-buck** [xdgurl/xdgurl#4]
Gnome Color Schemes
Plasma Widget Styles
Conky
Login Themes, like sddm, mdm, etc.

**Comment by akiraohgaki** [comment]
> Login Themes, like sddm, mdm, etc.

We should solve issue: https://github.com/xdgurl/xdgurl/issues/6 to install DM themes.

**Comment by akiraohgaki** [comment]
We should organize categories.

**Gnome Color Schemes?**
If it is for GTK, we can mapping to "themes" or "gtk2_themes" or "gtk3_themes"

**Plasma Widget Styles?**
If it is for QtCurve, we can mapping to "qtcurve"

**Conky Screenlets?**
Conky? Screenlets? we should be separate the category.

However, difficult to meke Conky theme installation, because it's need a manual configuration by user.

**Comment by star-buck** [comment]
What is the difference between conky and conky screenlets? are there any other conky stuff?

Plasma Widget styles is different than qtcurve, sometimes there are qtcurve themes in there, but it is wrong.

Gnome color schemes = i dont know if you can map them to themes.

**Comment by akiraohgaki** [comment]
Screenlets is a one of the desktop widget system. it's not Conky.
https://launchpad.net/screenlets
And you can find a screenlet (desktop widget for screenlets) in old post in category "Conky Screenlets".

I think that category name is sloppy...

**Comment by star-buck** [comment]
okay, renamed to Conky Themes, so we're not supporting "Screenlets"

**Comment by akiraohgaki** [comment]
> we're not supporting "Screenlets"

Alright.

**Comment by akiraohgaki** [comment]
Close for now.
Maybe we add new issue per types.
